// <auto-generated />
using System;
using BettingAI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BettingAI.Migrations
{
    [DbContext(typeof(BettingContext))]
    partial class BettingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("BettingAI.Models.Bet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AwayTeamCrest")
                        .HasColumnType("TEXT");

                    b.Property<string>("AwayTeamShort")
                        .HasColumnType("TEXT");

                    b.Property<string>("BetType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompetitionCode")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(3, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("EdgeAlignmentFeature")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FormAlignmentFeature")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeTeamCrest")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeTeamShort")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MatchUtcDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MomentumAlignmentFeature")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Odds")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reasoning")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.Property<string>("Selection")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Stake")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Winnings")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bets");
                });

            modelBuilder.Entity("BettingAI.Models.BetCombo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CombinedOdds")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(3, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Reasoning")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Stake")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Winnings")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BetCombos");
                });

            modelBuilder.Entity("BettingAI.Models.ComboLeg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AwayTeam")
                        .HasColumnType("TEXT");

                    b.Property<int>("BetComboId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AwayTeamCrest")
                        .HasColumnType("TEXT");

                    b.Property<string>("AwayTeamShort")
                        .HasColumnType("TEXT");

                    b.Property<string>("BetType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompetitionCode")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(3, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EdgeAlignmentFeature")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FormAlignmentFeature")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HomeTeam")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeTeamCrest")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeTeamShort")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MatchUtcDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MomentumAlignmentFeature")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Odds")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Selection")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BetComboId");

                    b.ToTable("ComboLegs");
                });

            modelBuilder.Entity("BettingAI.Models.LearnedModelWeights", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Bias")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("SampleCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WeightConfidence")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WeightEdgeAlignment")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WeightFormAlignment")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WeightMomentumAlignment")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LearnedModelWeights");
                });

            modelBuilder.Entity("BettingAI.Models.LearnedOddsStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AverageOdds")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("BetType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("SampleCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BetType")
                        .IsUnique();

                    b.ToTable("LearnedOddsStats");
                });

            modelBuilder.Entity("BettingAI.Models.LearningNotebook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AverageConfidence")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureAnalysis")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Patterns")
                        .HasColumnType("TEXT");

                    b.Property<string>("SuccessPatterns")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalBets")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WinRate")
                        .HasColumnType("TEXT");

                    b.Property<int>("WonBets")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LearningNotebook");
                });

            modelBuilder.Entity("BettingAI.Models.MatchContext", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Altitude")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AvgGoalsH2H")
                        .HasColumnType("TEXT");

                    b.Property<string>("AwayLineup")
                        .HasColumnType("TEXT");

                    b.Property<string>("AwayMissingPlayers")
                        .HasColumnType("TEXT");

                    b.Property<string>("AwayTeam")
                        .HasColumnType("TEXT");

                    b.Property<int>("AwayWinsH2H")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Competition")
                        .HasColumnType("TEXT");

                    b.Property<int>("DrawsH2H")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ExpectedScore")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HomeExpectedWinProbability")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeLineup")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeMissingPlayers")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeTeam")
                        .HasColumnType("TEXT");

                    b.Property<int>("HomeWinsH2H")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDerby")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEuropeanMatch")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Weather")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MatchContexts");
                });

            modelBuilder.Entity("BettingAI.Models.TeamRecentResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHome")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpponentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeamName");

                    b.ToTable("TeamRecentResults");
                });

            modelBuilder.Entity("BettingAI.Models.TeamStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CleanSheets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveMatches")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ConversionRate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DaysSinceLastMatch")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DefenseRating")
                        .HasColumnType("TEXT");

                    b.Property<int>("Draws")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("FatigueIndex")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FormLast5")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHomeMatch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyInjuries")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Losses")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PossessionAvg")
                        .HasColumnType("TEXT");

                    b.Property<int>("ShotsConceded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShotsOnTarget")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamName")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalShots")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("xA")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("xG")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("xGA")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TeamStats");
                });

            modelBuilder.Entity("BettingAI.Models.ComboLeg", b =>
                {
                    b.HasOne("BettingAI.Models.BetCombo", "BetCombo")
                        .WithMany("Legs")
                        .HasForeignKey("BetComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BetCombo");
                });

            modelBuilder.Entity("BettingAI.Models.BetCombo", b =>
                {
                    b.Navigation("Legs");
                });
#pragma warning restore 612, 618
        }
    }
}
