-- Backfill HomeTeamCrest/AwayTeamCrest on OLD Bets and ComboLegs rows
-- using the verified TeamCrests.cs dictionary. Matches directly on the
-- HomeTeam/AwayTeam text already stored (same official name used as the
-- dictionary key), only where the crest column is still NULL, so it's
-- safe to run more than once and doesn't require knowing row Ids.

-- Bets
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/98.png' WHERE HomeTeam='AC Milan' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/98.png' WHERE AwayTeam='AC Milan' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/99.png' WHERE HomeTeam='ACF Fiorentina' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/99.png' WHERE AwayTeam='ACF Fiorentina' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/100.png' WHERE HomeTeam='AS Roma' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/100.png' WHERE AwayTeam='AS Roma' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/102.png' WHERE HomeTeam='Atalanta BC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/102.png' WHERE AwayTeam='Atalanta BC' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/103.png' WHERE HomeTeam='Bologna FC 1909' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/103.png' WHERE AwayTeam='Bologna FC 1909' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/104.png' WHERE HomeTeam='Cagliari Calcio' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/104.png' WHERE AwayTeam='Cagliari Calcio' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/107.png' WHERE HomeTeam='Genoa CFC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/107.png' WHERE AwayTeam='Genoa CFC' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/108.png' WHERE HomeTeam='FC Internazionale Milano' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/108.png' WHERE AwayTeam='FC Internazionale Milano' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/109.png' WHERE HomeTeam='Juventus FC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/109.png' WHERE AwayTeam='Juventus FC' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/110.png' WHERE HomeTeam='SS Lazio' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/110.png' WHERE AwayTeam='SS Lazio' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/112.png' WHERE HomeTeam='Parma Calcio 1913' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/112.png' WHERE AwayTeam='Parma Calcio 1913' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/113.png' WHERE HomeTeam='SSC Napoli' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/113.png' WHERE AwayTeam='SSC Napoli' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/115.png' WHERE HomeTeam='Udinese Calcio' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/115.png' WHERE AwayTeam='Udinese Calcio' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/454.png' WHERE HomeTeam='Venezia FC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/454.png' WHERE AwayTeam='Venezia FC' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/470.png' WHERE HomeTeam='Frosinone Calcio' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/470.png' WHERE AwayTeam='Frosinone Calcio' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/471.png' WHERE HomeTeam='US Sassuolo Calcio' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/471.png' WHERE AwayTeam='US Sassuolo Calcio' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/586.png' WHERE HomeTeam='Torino FC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/586.png' WHERE AwayTeam='Torino FC' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/5890.png' WHERE HomeTeam='US Lecce' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/5890.png' WHERE AwayTeam='US Lecce' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/5911.png' WHERE HomeTeam='AC Monza' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/5911.png' WHERE AwayTeam='AC Monza' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/7397.png' WHERE HomeTeam='Como 1907' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/7397.png' WHERE AwayTeam='Como 1907' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/1.png' WHERE HomeTeam='1. FC Köln' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/1.png' WHERE AwayTeam='1. FC Köln' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/2.png' WHERE HomeTeam='TSG 1899 Hoffenheim' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/2.png' WHERE AwayTeam='TSG 1899 Hoffenheim' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/3.png' WHERE HomeTeam='Bayer 04 Leverkusen' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/3.png' WHERE AwayTeam='Bayer 04 Leverkusen' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/4.png' WHERE HomeTeam='Borussia Dortmund' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/4.png' WHERE AwayTeam='Borussia Dortmund' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/5.png' WHERE HomeTeam='FC Bayern München' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/5.png' WHERE AwayTeam='FC Bayern München' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/6.png' WHERE HomeTeam='FC Schalke 04' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/6.png' WHERE AwayTeam='FC Schalke 04' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/7.png' WHERE HomeTeam='Hamburger SV' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/7.png' WHERE AwayTeam='Hamburger SV' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/10.png' WHERE HomeTeam='VfB Stuttgart' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/10.png' WHERE AwayTeam='VfB Stuttgart' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/12.png' WHERE HomeTeam='SV Werder Bremen' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/12.png' WHERE AwayTeam='SV Werder Bremen' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/15.png' WHERE HomeTeam='1. FSV Mainz 05' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/15.png' WHERE AwayTeam='1. FSV Mainz 05' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/16.png' WHERE HomeTeam='FC Augsburg' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/16.png' WHERE AwayTeam='FC Augsburg' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/17.png' WHERE HomeTeam='SC Freiburg' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/17.png' WHERE AwayTeam='SC Freiburg' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/18.png' WHERE HomeTeam='Borussia Mönchengladbach' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/18.png' WHERE AwayTeam='Borussia Mönchengladbach' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/19.png' WHERE HomeTeam='Eintracht Frankfurt' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/19.png' WHERE AwayTeam='Eintracht Frankfurt' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/28.png' WHERE HomeTeam='1. FC Union Berlin' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/28.png' WHERE AwayTeam='1. FC Union Berlin' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/29.png' WHERE HomeTeam='SC Paderborn 07' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/29.png' WHERE AwayTeam='SC Paderborn 07' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/719.png' WHERE HomeTeam='SV 07 Elversberg' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/719.png' WHERE AwayTeam='SV 07 Elversberg' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/721.png' WHERE HomeTeam='RB Leipzig' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/721.png' WHERE AwayTeam='RB Leipzig' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/57.png' WHERE HomeTeam='Arsenal FC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/57.png' WHERE AwayTeam='Arsenal FC' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/58.png' WHERE HomeTeam='Aston Villa FC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/58.png' WHERE AwayTeam='Aston Villa FC' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/61.png' WHERE HomeTeam='Chelsea FC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/61.png' WHERE AwayTeam='Chelsea FC' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/62.png' WHERE HomeTeam='Everton FC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/62.png' WHERE AwayTeam='Everton FC' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/63.png' WHERE HomeTeam='Fulham FC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/63.png' WHERE AwayTeam='Fulham FC' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/64.png' WHERE HomeTeam='Liverpool FC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/64.png' WHERE AwayTeam='Liverpool FC' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/65.png' WHERE HomeTeam='Manchester City FC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/65.png' WHERE AwayTeam='Manchester City FC' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/66.png' WHERE HomeTeam='Manchester United FC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/66.png' WHERE AwayTeam='Manchester United FC' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/67.png' WHERE HomeTeam='Newcastle United FC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/67.png' WHERE AwayTeam='Newcastle United FC' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/71.png' WHERE HomeTeam='Sunderland AFC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/71.png' WHERE AwayTeam='Sunderland AFC' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/73.png' WHERE HomeTeam='Tottenham Hotspur FC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/73.png' WHERE AwayTeam='Tottenham Hotspur FC' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/322.png' WHERE HomeTeam='Hull City AFC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/322.png' WHERE AwayTeam='Hull City AFC' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/341.png' WHERE HomeTeam='Leeds United FC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/341.png' WHERE AwayTeam='Leeds United FC' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/349.png' WHERE HomeTeam='Ipswich Town FC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/349.png' WHERE AwayTeam='Ipswich Town FC' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/351.png' WHERE HomeTeam='Nottingham Forest FC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/351.png' WHERE AwayTeam='Nottingham Forest FC' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/354.png' WHERE HomeTeam='Crystal Palace FC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/354.png' WHERE AwayTeam='Crystal Palace FC' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/397.png' WHERE HomeTeam='Brighton & Hove Albion FC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/397.png' WHERE AwayTeam='Brighton & Hove Albion FC' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/402.png' WHERE HomeTeam='Brentford FC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/402.png' WHERE AwayTeam='Brentford FC' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/bournemouth.png' WHERE HomeTeam='AFC Bournemouth' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/bournemouth.png' WHERE AwayTeam='AFC Bournemouth' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/1076.png' WHERE HomeTeam='Coventry City FC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/1076.png' WHERE AwayTeam='Coventry City FC' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/77.png' WHERE HomeTeam='Athletic Club' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/77.png' WHERE AwayTeam='Athletic Club' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/78.png' WHERE HomeTeam='Club Atlético de Madrid' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/78.png' WHERE AwayTeam='Club Atlético de Madrid' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/79.png' WHERE HomeTeam='CA Osasuna' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/79.png' WHERE AwayTeam='CA Osasuna' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/80.png' WHERE HomeTeam='RCD Espanyol de Barcelona' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/80.png' WHERE AwayTeam='RCD Espanyol de Barcelona' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/81.png' WHERE HomeTeam='FC Barcelona' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/81.png' WHERE AwayTeam='FC Barcelona' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/82.png' WHERE HomeTeam='Getafe CF' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/82.png' WHERE AwayTeam='Getafe CF' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/84.png' WHERE HomeTeam='Málaga CF' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/84.png' WHERE AwayTeam='Málaga CF' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/86.png' WHERE HomeTeam='Real Madrid CF' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/86.png' WHERE AwayTeam='Real Madrid CF' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/87.png' WHERE HomeTeam='Rayo Vallecano de Madrid' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/87.png' WHERE AwayTeam='Rayo Vallecano de Madrid' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/88.png' WHERE HomeTeam='Levante UD' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/88.png' WHERE AwayTeam='Levante UD' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/90.png' WHERE HomeTeam='Real Betis Balompié' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/90.png' WHERE AwayTeam='Real Betis Balompié' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/92.png' WHERE HomeTeam='Real Sociedad de Fútbol' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/92.png' WHERE AwayTeam='Real Sociedad de Fútbol' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/94.png' WHERE HomeTeam='Villarreal CF' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/94.png' WHERE AwayTeam='Villarreal CF' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/95.png' WHERE HomeTeam='Valencia CF' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/95.png' WHERE AwayTeam='Valencia CF' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/263.png' WHERE HomeTeam='Deportivo Alavés' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/263.png' WHERE AwayTeam='Deportivo Alavés' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/285.png' WHERE HomeTeam='Elche CF' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/285.png' WHERE AwayTeam='Elche CF' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/558.png' WHERE HomeTeam='RC Celta de Vigo' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/558.png' WHERE AwayTeam='RC Celta de Vigo' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/559.png' WHERE HomeTeam='Sevilla FC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/559.png' WHERE AwayTeam='Sevilla FC' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/560.png' WHERE HomeTeam='RC Deportivo La Coruña' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/560.png' WHERE AwayTeam='RC Deportivo La Coruña' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/5335.png' WHERE HomeTeam='Real Racing Club de Santander' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/5335.png' WHERE AwayTeam='Real Racing Club de Santander' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/511.png' WHERE HomeTeam='Toulouse FC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/511.png' WHERE AwayTeam='Toulouse FC' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/512.png' WHERE HomeTeam='Stade Brestois 29' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/512.png' WHERE AwayTeam='Stade Brestois 29' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/516.png' WHERE HomeTeam='Olympique de Marseille' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/516.png' WHERE AwayTeam='Olympique de Marseille' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/519.png' WHERE HomeTeam='AJ Auxerre' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/519.png' WHERE AwayTeam='AJ Auxerre' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/521.png' WHERE HomeTeam='Lille OSC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/521.png' WHERE AwayTeam='Lille OSC' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/522.png' WHERE HomeTeam='OGC Nice' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/522.png' WHERE AwayTeam='OGC Nice' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/523.png' WHERE HomeTeam='Olympique Lyonnais' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/523.png' WHERE AwayTeam='Olympique Lyonnais' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/524.png' WHERE HomeTeam='Paris Saint-Germain FC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/524.png' WHERE AwayTeam='Paris Saint-Germain FC' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/525.png' WHERE HomeTeam='FC Lorient' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/525.png' WHERE AwayTeam='FC Lorient' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/529.png' WHERE HomeTeam='Stade Rennais FC 1901' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/529.png' WHERE AwayTeam='Stade Rennais FC 1901' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/531.png' WHERE HomeTeam='ES Troyes AC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/531.png' WHERE AwayTeam='ES Troyes AC' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/532.png' WHERE HomeTeam='Angers SCO' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/532.png' WHERE AwayTeam='Angers SCO' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/533.png' WHERE HomeTeam='Le Havre AC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/533.png' WHERE AwayTeam='Le Havre AC' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://upload.wikimedia.org/wikipedia/en/5/57/Le_Mans_FC_logo.svg' WHERE HomeTeam='Le Mans FC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://upload.wikimedia.org/wikipedia/en/5/57/Le_Mans_FC_logo.svg' WHERE AwayTeam='Le Mans FC' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/546.png' WHERE HomeTeam='Racing Club de Lens' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/546.png' WHERE AwayTeam='Racing Club de Lens' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/548.png' WHERE HomeTeam='AS Monaco FC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/548.png' WHERE AwayTeam='AS Monaco FC' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/576.png' WHERE HomeTeam='RC Strasbourg Alsace' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/576.png' WHERE AwayTeam='RC Strasbourg Alsace' AND AwayTeamCrest IS NULL;
UPDATE Bets SET HomeTeamCrest='https://crests.football-data.org/1045.png' WHERE HomeTeam='Paris FC' AND HomeTeamCrest IS NULL;
UPDATE Bets SET AwayTeamCrest='https://crests.football-data.org/1045.png' WHERE AwayTeam='Paris FC' AND AwayTeamCrest IS NULL;

-- ComboLegs
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/98.png' WHERE HomeTeam='AC Milan' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/98.png' WHERE AwayTeam='AC Milan' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/99.png' WHERE HomeTeam='ACF Fiorentina' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/99.png' WHERE AwayTeam='ACF Fiorentina' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/100.png' WHERE HomeTeam='AS Roma' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/100.png' WHERE AwayTeam='AS Roma' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/102.png' WHERE HomeTeam='Atalanta BC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/102.png' WHERE AwayTeam='Atalanta BC' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/103.png' WHERE HomeTeam='Bologna FC 1909' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/103.png' WHERE AwayTeam='Bologna FC 1909' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/104.png' WHERE HomeTeam='Cagliari Calcio' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/104.png' WHERE AwayTeam='Cagliari Calcio' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/107.png' WHERE HomeTeam='Genoa CFC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/107.png' WHERE AwayTeam='Genoa CFC' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/108.png' WHERE HomeTeam='FC Internazionale Milano' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/108.png' WHERE AwayTeam='FC Internazionale Milano' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/109.png' WHERE HomeTeam='Juventus FC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/109.png' WHERE AwayTeam='Juventus FC' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/110.png' WHERE HomeTeam='SS Lazio' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/110.png' WHERE AwayTeam='SS Lazio' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/112.png' WHERE HomeTeam='Parma Calcio 1913' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/112.png' WHERE AwayTeam='Parma Calcio 1913' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/113.png' WHERE HomeTeam='SSC Napoli' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/113.png' WHERE AwayTeam='SSC Napoli' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/115.png' WHERE HomeTeam='Udinese Calcio' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/115.png' WHERE AwayTeam='Udinese Calcio' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/454.png' WHERE HomeTeam='Venezia FC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/454.png' WHERE AwayTeam='Venezia FC' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/470.png' WHERE HomeTeam='Frosinone Calcio' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/470.png' WHERE AwayTeam='Frosinone Calcio' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/471.png' WHERE HomeTeam='US Sassuolo Calcio' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/471.png' WHERE AwayTeam='US Sassuolo Calcio' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/586.png' WHERE HomeTeam='Torino FC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/586.png' WHERE AwayTeam='Torino FC' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/5890.png' WHERE HomeTeam='US Lecce' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/5890.png' WHERE AwayTeam='US Lecce' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/5911.png' WHERE HomeTeam='AC Monza' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/5911.png' WHERE AwayTeam='AC Monza' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/7397.png' WHERE HomeTeam='Como 1907' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/7397.png' WHERE AwayTeam='Como 1907' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/1.png' WHERE HomeTeam='1. FC Köln' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/1.png' WHERE AwayTeam='1. FC Köln' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/2.png' WHERE HomeTeam='TSG 1899 Hoffenheim' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/2.png' WHERE AwayTeam='TSG 1899 Hoffenheim' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/3.png' WHERE HomeTeam='Bayer 04 Leverkusen' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/3.png' WHERE AwayTeam='Bayer 04 Leverkusen' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/4.png' WHERE HomeTeam='Borussia Dortmund' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/4.png' WHERE AwayTeam='Borussia Dortmund' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/5.png' WHERE HomeTeam='FC Bayern München' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/5.png' WHERE AwayTeam='FC Bayern München' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/6.png' WHERE HomeTeam='FC Schalke 04' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/6.png' WHERE AwayTeam='FC Schalke 04' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/7.png' WHERE HomeTeam='Hamburger SV' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/7.png' WHERE AwayTeam='Hamburger SV' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/10.png' WHERE HomeTeam='VfB Stuttgart' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/10.png' WHERE AwayTeam='VfB Stuttgart' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/12.png' WHERE HomeTeam='SV Werder Bremen' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/12.png' WHERE AwayTeam='SV Werder Bremen' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/15.png' WHERE HomeTeam='1. FSV Mainz 05' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/15.png' WHERE AwayTeam='1. FSV Mainz 05' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/16.png' WHERE HomeTeam='FC Augsburg' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/16.png' WHERE AwayTeam='FC Augsburg' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/17.png' WHERE HomeTeam='SC Freiburg' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/17.png' WHERE AwayTeam='SC Freiburg' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/18.png' WHERE HomeTeam='Borussia Mönchengladbach' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/18.png' WHERE AwayTeam='Borussia Mönchengladbach' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/19.png' WHERE HomeTeam='Eintracht Frankfurt' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/19.png' WHERE AwayTeam='Eintracht Frankfurt' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/28.png' WHERE HomeTeam='1. FC Union Berlin' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/28.png' WHERE AwayTeam='1. FC Union Berlin' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/29.png' WHERE HomeTeam='SC Paderborn 07' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/29.png' WHERE AwayTeam='SC Paderborn 07' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/719.png' WHERE HomeTeam='SV 07 Elversberg' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/719.png' WHERE AwayTeam='SV 07 Elversberg' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/721.png' WHERE HomeTeam='RB Leipzig' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/721.png' WHERE AwayTeam='RB Leipzig' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/57.png' WHERE HomeTeam='Arsenal FC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/57.png' WHERE AwayTeam='Arsenal FC' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/58.png' WHERE HomeTeam='Aston Villa FC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/58.png' WHERE AwayTeam='Aston Villa FC' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/61.png' WHERE HomeTeam='Chelsea FC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/61.png' WHERE AwayTeam='Chelsea FC' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/62.png' WHERE HomeTeam='Everton FC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/62.png' WHERE AwayTeam='Everton FC' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/63.png' WHERE HomeTeam='Fulham FC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/63.png' WHERE AwayTeam='Fulham FC' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/64.png' WHERE HomeTeam='Liverpool FC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/64.png' WHERE AwayTeam='Liverpool FC' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/65.png' WHERE HomeTeam='Manchester City FC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/65.png' WHERE AwayTeam='Manchester City FC' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/66.png' WHERE HomeTeam='Manchester United FC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/66.png' WHERE AwayTeam='Manchester United FC' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/67.png' WHERE HomeTeam='Newcastle United FC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/67.png' WHERE AwayTeam='Newcastle United FC' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/71.png' WHERE HomeTeam='Sunderland AFC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/71.png' WHERE AwayTeam='Sunderland AFC' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/73.png' WHERE HomeTeam='Tottenham Hotspur FC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/73.png' WHERE AwayTeam='Tottenham Hotspur FC' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/322.png' WHERE HomeTeam='Hull City AFC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/322.png' WHERE AwayTeam='Hull City AFC' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/341.png' WHERE HomeTeam='Leeds United FC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/341.png' WHERE AwayTeam='Leeds United FC' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/349.png' WHERE HomeTeam='Ipswich Town FC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/349.png' WHERE AwayTeam='Ipswich Town FC' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/351.png' WHERE HomeTeam='Nottingham Forest FC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/351.png' WHERE AwayTeam='Nottingham Forest FC' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/354.png' WHERE HomeTeam='Crystal Palace FC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/354.png' WHERE AwayTeam='Crystal Palace FC' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/397.png' WHERE HomeTeam='Brighton & Hove Albion FC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/397.png' WHERE AwayTeam='Brighton & Hove Albion FC' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/402.png' WHERE HomeTeam='Brentford FC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/402.png' WHERE AwayTeam='Brentford FC' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/bournemouth.png' WHERE HomeTeam='AFC Bournemouth' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/bournemouth.png' WHERE AwayTeam='AFC Bournemouth' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/1076.png' WHERE HomeTeam='Coventry City FC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/1076.png' WHERE AwayTeam='Coventry City FC' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/77.png' WHERE HomeTeam='Athletic Club' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/77.png' WHERE AwayTeam='Athletic Club' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/78.png' WHERE HomeTeam='Club Atlético de Madrid' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/78.png' WHERE AwayTeam='Club Atlético de Madrid' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/79.png' WHERE HomeTeam='CA Osasuna' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/79.png' WHERE AwayTeam='CA Osasuna' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/80.png' WHERE HomeTeam='RCD Espanyol de Barcelona' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/80.png' WHERE AwayTeam='RCD Espanyol de Barcelona' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/81.png' WHERE HomeTeam='FC Barcelona' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/81.png' WHERE AwayTeam='FC Barcelona' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/82.png' WHERE HomeTeam='Getafe CF' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/82.png' WHERE AwayTeam='Getafe CF' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/84.png' WHERE HomeTeam='Málaga CF' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/84.png' WHERE AwayTeam='Málaga CF' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/86.png' WHERE HomeTeam='Real Madrid CF' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/86.png' WHERE AwayTeam='Real Madrid CF' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/87.png' WHERE HomeTeam='Rayo Vallecano de Madrid' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/87.png' WHERE AwayTeam='Rayo Vallecano de Madrid' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/88.png' WHERE HomeTeam='Levante UD' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/88.png' WHERE AwayTeam='Levante UD' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/90.png' WHERE HomeTeam='Real Betis Balompié' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/90.png' WHERE AwayTeam='Real Betis Balompié' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/92.png' WHERE HomeTeam='Real Sociedad de Fútbol' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/92.png' WHERE AwayTeam='Real Sociedad de Fútbol' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/94.png' WHERE HomeTeam='Villarreal CF' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/94.png' WHERE AwayTeam='Villarreal CF' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/95.png' WHERE HomeTeam='Valencia CF' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/95.png' WHERE AwayTeam='Valencia CF' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/263.png' WHERE HomeTeam='Deportivo Alavés' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/263.png' WHERE AwayTeam='Deportivo Alavés' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/285.png' WHERE HomeTeam='Elche CF' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/285.png' WHERE AwayTeam='Elche CF' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/558.png' WHERE HomeTeam='RC Celta de Vigo' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/558.png' WHERE AwayTeam='RC Celta de Vigo' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/559.png' WHERE HomeTeam='Sevilla FC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/559.png' WHERE AwayTeam='Sevilla FC' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/560.png' WHERE HomeTeam='RC Deportivo La Coruña' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/560.png' WHERE AwayTeam='RC Deportivo La Coruña' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/5335.png' WHERE HomeTeam='Real Racing Club de Santander' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/5335.png' WHERE AwayTeam='Real Racing Club de Santander' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/511.png' WHERE HomeTeam='Toulouse FC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/511.png' WHERE AwayTeam='Toulouse FC' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/512.png' WHERE HomeTeam='Stade Brestois 29' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/512.png' WHERE AwayTeam='Stade Brestois 29' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/516.png' WHERE HomeTeam='Olympique de Marseille' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/516.png' WHERE AwayTeam='Olympique de Marseille' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/519.png' WHERE HomeTeam='AJ Auxerre' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/519.png' WHERE AwayTeam='AJ Auxerre' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/521.png' WHERE HomeTeam='Lille OSC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/521.png' WHERE AwayTeam='Lille OSC' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/522.png' WHERE HomeTeam='OGC Nice' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/522.png' WHERE AwayTeam='OGC Nice' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/523.png' WHERE HomeTeam='Olympique Lyonnais' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/523.png' WHERE AwayTeam='Olympique Lyonnais' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/524.png' WHERE HomeTeam='Paris Saint-Germain FC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/524.png' WHERE AwayTeam='Paris Saint-Germain FC' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/525.png' WHERE HomeTeam='FC Lorient' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/525.png' WHERE AwayTeam='FC Lorient' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/529.png' WHERE HomeTeam='Stade Rennais FC 1901' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/529.png' WHERE AwayTeam='Stade Rennais FC 1901' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/531.png' WHERE HomeTeam='ES Troyes AC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/531.png' WHERE AwayTeam='ES Troyes AC' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/532.png' WHERE HomeTeam='Angers SCO' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/532.png' WHERE AwayTeam='Angers SCO' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/533.png' WHERE HomeTeam='Le Havre AC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/533.png' WHERE AwayTeam='Le Havre AC' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://upload.wikimedia.org/wikipedia/en/5/57/Le_Mans_FC_logo.svg' WHERE HomeTeam='Le Mans FC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://upload.wikimedia.org/wikipedia/en/5/57/Le_Mans_FC_logo.svg' WHERE AwayTeam='Le Mans FC' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/546.png' WHERE HomeTeam='Racing Club de Lens' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/546.png' WHERE AwayTeam='Racing Club de Lens' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/548.png' WHERE HomeTeam='AS Monaco FC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/548.png' WHERE AwayTeam='AS Monaco FC' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/576.png' WHERE HomeTeam='RC Strasbourg Alsace' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/576.png' WHERE AwayTeam='RC Strasbourg Alsace' AND AwayTeamCrest IS NULL;
UPDATE ComboLegs SET HomeTeamCrest='https://crests.football-data.org/1045.png' WHERE HomeTeam='Paris FC' AND HomeTeamCrest IS NULL;
UPDATE ComboLegs SET AwayTeamCrest='https://crests.football-data.org/1045.png' WHERE AwayTeam='Paris FC' AND AwayTeamCrest IS NULL;

